default:
    just --list

alias b := build-img

arch_x64 := "amd64"
arch_arm64 := "arm64"
tag := "harmlesstech/rust:"

# Builds all images for all archs
build: alpine debian ubuntu

# Builds an image
build-img FOLDER TAG ARCH:
   docker build --pull --platform linux/{{ARCH}} -t {{TAG}} {{FOLDER}}
# --no-cache --progress plain

### Alpine

# Builds all alpine images
alpine: alpine-latest alpine-3-15 alpine-3-14

alpine_folder := "./alpine"
alpine_tag := tag + "alpine-"

# Builds latest alpine images
alpine-latest: alpine-latest-x64 alpine-latest-arm64

alpine_latest := alpine_tag + "latest"

alpine-latest-x64:
    just b {{alpine_folder}} {{alpine_latest}} {{arch_x64}}

alpine-latest-arm64:
    just b {{alpine_folder}} {{alpine_latest}} {{arch_arm64}}

# Builds 3.15 alpine images
alpine-3-15: alpine-3-15-x64 alpine-3-15-arm64

alpine_3_15_folder := alpine_folder / "3.15"
alpine_3_15 := alpine_tag + "3.15"

alpine-3-15-x64:
    just b {{alpine_3_15_folder}} {{alpine_3_15}} {{arch_x64}}

alpine-3-15-arm64:
    just b {{alpine_3_15_folder}} {{alpine_3_15}} {{arch_arm64}}

# Builds 3.14 alpine images
alpine-3-14: alpine-3-14-x64 alpine-3-14-arm64

alpine_3_14_folder := alpine_folder / "3.14"
alpine_3_14 := alpine_tag + "3.14"

alpine-3-14-x64:
    just b {{alpine_3_14_folder}} {{alpine_3_14}} {{arch_x64}}

alpine-3-14-arm64:
    just b {{alpine_3_14_folder}} {{alpine_3_14}} {{arch_arm64}}

### AmazonLinux

### Debian

# Builds all debian images
debian: debian-latest debian-bullseye-slim debian-buster debian-buster-slim

debian_folder := "./debian"
debian_tag := tag + "debian-"

# Builds latest debian images
debian-latest: debian-latest-x64 debian-latest-arm64

debian_latest := debian_tag + "latest"

debian-latest-x64:
    just b {{debian_folder}} {{debian_latest}} {{arch_x64}}

debian-latest-arm64:
    just b {{debian_folder}} {{debian_latest}} {{arch_arm64}}

# Builds bullseye slim debian images
debian-bullseye-slim: debian-bullseye-slim-x64 debian-bullseye-slim-arm64

debian_bullseye_slim_folder := debian_folder / "bullseye/slim"
debian_bullseye_slim := debian_tag + "bullseye-slim"

debian-bullseye-slim-x64:
    just b {{debian_bullseye_slim_folder}} {{debian_bullseye_slim}} {{arch_x64}}

debian-bullseye-slim-arm64:
    just b {{debian_bullseye_slim_folder}} {{debian_bullseye_slim}} {{arch_arm64}}

# Builds buster debian images
debian-buster: debian-buster-x64 debian-buster-arm64

debian_buster_folder := debian_folder / "buster"
debian_buster := debian_tag + "buster"

debian-buster-x64:
    just b {{debian_buster_folder}} {{debian_buster}} {{arch_x64}}

debian-buster-arm64:
    just b {{debian_buster_folder}} {{debian_buster}} {{arch_arm64}}

# Builds buster slim debian images
debian-buster-slim: debian-buster-slim-x64 debian-buster-slim-arm64

debian_buster_slim_folder := debian_buster_folder / "slim"
debian_buster_slim := debian_buster + "-slim"

debian-buster-slim-x64:
    just b {{debian_buster_slim_folder}} {{debian_buster_slim}} {{arch_x64}}

debian-buster-slim-arm64:
    just b {{debian_buster_slim_folder}} {{debian_buster_slim}} {{arch_arm64}}

### OracleLinux

### Photon

### RockyLinux

### Ubuntu

# Builds all ubuntu images
ubuntu: ubuntu-latest ubuntu-focal

ubuntu_folder := "./ubuntu"
ubuntu_tag := tag + "ubuntu-"

# Builds latest ubuntu images
ubuntu-latest: ubuntu-latest-x64 ubuntu-latest-arm64

ubuntu_latest := ubuntu_tag + "latest"

ubuntu-latest-x64:
    just b {{ubuntu_folder}} {{ubuntu_latest}} {{arch_x64}}

ubuntu-latest-arm64:
    just b {{ubuntu_folder}} {{ubuntu_latest}} {{arch_arm64}}

# Builds focal ubuntu images
ubuntu-focal: ubuntu-focal-x64 ubuntu-focal-arm64

ubuntu_focal_folder := debian_folder / "focal"
ubuntu_focal := debian_tag + "focal"

ubuntu-focal-x64:
    just b {{ubuntu_focal_folder}} {{ubuntu_focal}} {{arch_x64}}

ubuntu-focal-arm64:
    just b {{ubuntu_focal_folder}} {{ubuntu_focal}} {{arch_arm64}}
