name: Build Rust Images
description: Builds docker images for harmless/rust

on:
  push:
    branches: [ main ]
    paths: [ rust/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 0'


defaults:
  run:
    working-directory: ./rust

env:
  img: 'harmless/rust:'

runs:
  build:
    strategy:
      matrix:
        include:
          - context: ./alpine
            tag: alpine-latest
          - context: ./debian
            tag: debian-latest
    runs-on: ubuntu-latest
    steps:
      - name: Get Rust Version
        run: |
          echo "rust_version=$(rustc -vV | grep "^release: " | cut -c 10-)" >> $GITHUB_ENV
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          no-cache: true
          pull: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.img }}${{ matrix.tag }},${{ env.img }}${{ env.rust_version }}-${{ matrix.tag }}

